services:
  app:
    build: .
    env_file: .env.docker
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/database/database.sqlite
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
      - ./coverage:/var/www/public/coverage